# Generated by Django 6.0.3 on 2026-04-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quanLySanPham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('KM_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('KM_GiaTri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('KM_NgayBD', models.DateField()),
                ('KM_NgayKT', models.DateField()),
                ('KM_Ten', models.CharField(max_length=100)),
                ('KM_Loai', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham_KhuyenMai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KM_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLyKhuyenMai.khuyenmai')),
                ('SP_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanLySanPham.sanpham')),
            ],
            options={
                'unique_together': {('SP_Ma', 'KM_Ma')},
            },
        ),
    ]
