# Generated by Django 6.0.3 on 2026-04-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('KH_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('KH_Ten', models.CharField(max_length=100)),
                ('KH_TongChiTieu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('KH_SoDonHang', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietKhachHang',
            fields=[
                ('CTKH_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('CTKH_HoTenNguoiNhan', models.CharField(max_length=100)),
                ('CTKH_SDT', models.CharField(max_length=10)),
                ('CTKH_DiaChi', models.TextField()),
                ('KH_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanLyKhachHang.khachhang')),
            ],
        ),
    ]
