# Generated by Django 6.0.3 on 2026-04-13 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gioHang', '0001_initial'),
        ('quanLyKhachHang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonDat',
            fields=[
                ('TT_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('TT_TongPhiVC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TT_TongThanhToan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DH_TrangThai', models.CharField(max_length=50)),
                ('TT_PhuongThuc', models.CharField(max_length=100)),
                ('TT_TongTienHang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TT_NgayThanhToan', models.DateField(blank=True, null=True)),
                ('TT_NgayDatHang', models.DateField(auto_now_add=True)),
                ('CTKH_Ma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanLyKhachHang.chitietkhachhang')),
                ('GH_Ma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gioHang.giohang')),
            ],
        ),
    ]
