# Generated by Django 6.0.3 on 2026-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('NCC_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('NCC_Ten', models.CharField(max_length=100)),
                ('NCC_SDT', models.CharField(max_length=10)),
                ('NCC_DChi', models.TextField()),
            ],
        ),
    ]
