# Generated by Django 6.0.3 on 2026-04-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuanLyNhaCungCap', '0001_initial'),
        ('quanLySanPham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhapHang',
            fields=[
                ('NH_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('NH_Ngay', models.DateField(auto_now_add=True)),
                ('NH_TongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NCC_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLyNhaCungCap.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietNhapHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NH_DonGia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NH_SL', models.IntegerField()),
                ('NH_TTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BTSP_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanLySanPham.bienthesanpham')),
                ('NH_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLyNhapHang.nhaphang')),
            ],
            options={
                'unique_together': {('BTSP_Ma', 'NH_Ma')},
            },
        ),
    ]
