# Generated by Django 6.0.3 on 2026-04-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuanLyDanhMuc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('SP_Ma', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SP_Ten', models.CharField(max_length=100)),
                ('SP_GiaBan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SP_MoTa', models.TextField(blank=True, null=True)),
                ('SP_URLHinhAnh', models.URLField(blank=True, max_length=500, null=True)),
                ('SP_TrangThai', models.IntegerField(choices=[(0, 'Đang bán'), (1, 'Hết hàng'), (2, 'Ngừng bán')], default=0)),
                ('DM_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_pham_thuoc_dm', to='QuanLyDanhMuc.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='BienTheSanPham',
            fields=[
                ('BTSP_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('SP_SL', models.IntegerField(default=0)),
                ('SP_KichThuoc', models.CharField(max_length=5)),
                ('SP_MauSac', models.CharField(max_length=20)),
                ('SP_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanLySanPham.sanpham')),
            ],
        ),
    ]
