# Generated by Django 6.0.4 on 2026-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanLySanPham', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='SP_URLHinhAnh',
        ),
        migrations.AddField(
            model_name='sanpham',
            name='SP_HinhAnh',
            field=models.ImageField(blank=True, null=True, upload_to='sanpham/'),
        ),
    ]
