# Generated by Django 6.0.4 on 2026-04-13 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donDat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHangVanChuyen',
            fields=[
                ('DH_MaVanChuyen', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('DH_DViVanChuyen', models.CharField(max_length=200)),
                ('DH_PhiCuoc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TT_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donDat.dondat')),
            ],
        ),
    ]
