# Generated by Django 6.0.3 on 2026-04-13 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donDat', '0001_initial'),
        ('quanLyDonHang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhangvanchuyen',
            name='TT_Ma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donDat.dondat'),
        ),
        migrations.DeleteModel(
            name='DonDat',
        ),
    ]
