# Generated by Django 4.2.8 on 2026-03-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('DM_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('DM_Ten', models.CharField(max_length=100)),
                ('DM_Thuoc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatHang',
            fields=[
                ('DH_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('DH_Ngay', models.DateField(auto_now_add=True)),
                ('DH_TongSL', models.IntegerField()),
                ('DH_TrangThai', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('GH_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('GH_TamTinh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GH_TongSL', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('KH_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('KH_Ten', models.CharField(max_length=100)),
                ('KH_SDT', models.CharField(max_length=10)),
                ('KH_DiaChi', models.TextField()),
                ('KH_TongChiTieu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('KH_SoDonHang', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('KM_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('KM_GiaTri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('KM_NgayBD', models.DateField()),
                ('KM_NgayKT', models.DateField()),
                ('KM_Ten', models.CharField(max_length=100)),
                ('KM_Loai', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('NCC_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('NCC_Ten', models.CharField(max_length=100)),
                ('NCC_SDT', models.CharField(max_length=10)),
                ('NCC_DChi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('SP_Ma', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SP_Ten', models.CharField(max_length=100)),
                ('SP_GiaBan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SP_MoTa', models.TextField(blank=True, null=True)),
                ('SP_URLHinhAnh', models.URLField(blank=True, max_length=500, null=True)),
                ('SP_TrangThai', models.CharField(max_length=50)),
                ('DM_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_pham_thuoc_dm', to='app.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('TT_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('TT_HoTen', models.CharField(max_length=100)),
                ('TT_SDT', models.CharField(max_length=10)),
                ('TT_DiaChi', models.TextField()),
                ('TT_PhuongThuc', models.CharField(max_length=50)),
                ('TT_TongTienHang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TT_TongPhiVC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TT_TongThanhToan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GH_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.giohang')),
            ],
        ),
        migrations.CreateModel(
            name='NhapHang',
            fields=[
                ('NH_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('NH_Ngay', models.DateField(auto_now_add=True)),
                ('NH_TongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NCC_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='DonHangVanChuyen',
            fields=[
                ('DH_MaVanChuyen', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('DH_DViVanChuyen', models.CharField(max_length=100)),
                ('DH_PhiCuoc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DH_Ma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.dathang')),
            ],
        ),
        migrations.AddField(
            model_name='dathang',
            name='KH_Ma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.khachhang'),
        ),
        migrations.AddField(
            model_name='dathang',
            name='TT_Ma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.thanhtoan'),
        ),
        migrations.CreateModel(
            name='BienTheSanPham',
            fields=[
                ('BTSP_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('SP_SL', models.IntegerField(default=0)),
                ('SP_KichThuoc', models.CharField(max_length=5)),
                ('SP_MauSac', models.CharField(max_length=20)),
                ('SP_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham_KhuyenMai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KM_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.khuyenmai')),
                ('SP_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanpham')),
            ],
            options={
                'unique_together': {('SP_Ma', 'KM_Ma')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietNhapHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NH_DonGia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NH_SL', models.IntegerField()),
                ('NH_TTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BTSP_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bienthesanpham')),
                ('NH_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nhaphang')),
            ],
            options={
                'unique_together': {('BTSP_Ma', 'NH_Ma')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietGioHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GH_SL', models.IntegerField(default=1)),
                ('GH_TTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GH_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.giohang')),
                ('SP_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanpham')),
            ],
            options={
                'unique_together': {('GH_Ma', 'SP_Ma')},
            },
        ),
    ]
