# Generated by Django 6.0.3 on 2026-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('DM_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('DM_Ten', models.CharField(max_length=100)),
                ('DM_Thuoc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
