# Generated by Django 6.0.3 on 2026-04-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuanLyKhachHang', '0001_initial'),
        ('quanLySanPham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('GH_Ma', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('GH_TongSL', models.IntegerField(default=0)),
                ('GH_TamTinh', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('KH_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLyKhachHang.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietGioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GH_SL', models.IntegerField(default=1)),
                ('GH_TTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SP_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanLySanPham.sanpham')),
                ('GH_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gioHang.giohang')),
            ],
            options={
                'unique_together': {('GH_Ma', 'SP_Ma')},
            },
        ),
    ]
