# Generated by Django 4.2.8 on 2026-04-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gioHang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietgiohang',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
